// core/examples/luigi-sample-vue/src/views/projects/components/modal.vue
<template>
  <div v-if="visible" class="fd-ui__overlay fd-overlay fd-overlay--modal" aria-hidden="false">
    <div class="fd-modal" role="dialog">
      <div class="fd-modal__content" role="document">
        <header class="fd-modal__header">
          <slot name="header">
            <h1 class="fd-modal__title">Modal Header</h1>
            <button @click="hide" class=" fd-button--secondary fd-modal__close"></button>
          </slot>
        </header>
        <div class="fd-modal__body">
          <slot></slot>
        </div>
        <footer class="fd-modal__footer">
          <slot name="footer">
            <div class="fd-modal__actions">
              <button @click="hide" class=" fd-button--secondary">Cancel</button>
              <button @click="hide" class=" fd-button--primary">Confirm</button>
            </div>
          </slot>
        </footer>
      </div>
    </div>
  </div>
</template>

<script>
  import LuigiClient from '@kyma-project/luigi-client';

  export default {
    name: "modal",
    data: () => ({
      visible: false
    }),
    methods: {
      show () {
        this.visible = true
        this.luigiClient.uxManager().addBackdrop();
      },
      hide () {
        this.visible = false
        this.luigiClient.uxManager().removeBackdrop();
      },
    },
    mounted () {
      this.luigiClient = LuigiClient;
    },
    watch: {
      visible: function (val) {
        this.$emit('visibleChange', val)
      }
    }
  }
</script>

<style lang="scss" scoped>
  $fd-icons-path: "~fundamental-ui/scss/icons/";
  $left-nav-width: 320px;

  @import '~fundamental-ui/scss/icons';
  @import '~fundamental-ui/scss/layout/overlay';
  @import '~fundamental-ui/scss/components/modal';
  @import '~fundamental-ui/scss/components/button';

</style>

// core/examples/luigi-sample-angular/src/app/project/modal/modal.component.ts
import {
  Component,
  OnChanges,
  Input,
  Output,
  EventEmitter,
  SimpleChanges
} from '@angular/core';

import { LuigiClient } from '@kyma-project/luigi-client';

@Component({
  selector: 'app-modal',
  templateUrl: './modal.component.html',
  styleUrls: ['./modal.component.scss']
})
export class ModalComponent implements OnChanges {
  @Input() public modalActive: boolean;
  @Output() private modalClosed: EventEmitter<null>;
  private luigiClient: LuigiClient;

  public constructor() {
    this.luigiClient = LuigiClient;
    this.modalClosed = new EventEmitter<null>();
  }

  public ngOnChanges(changes: SimpleChanges): void {
    if (changes.modalActive.currentValue === true) {
      this.openModal();
    }
  }

  private openModal() {
    this.luigiClient.uxManager().addBackdrop();
  }

  public onCloseModalClick() {
    this.modalClosed.emit();
    this.luigiClient.uxManager().removeBackdrop();
  }
}

<div  *ngIf="modalActive" class="fd-ui__overlay fd-overlay fd-overlay--modal" aria-hidden="false">
  <div class="fd-modal" role="dialog">
    <div class="fd-modal__content" role="document">
      <header class="fd-modal__header">
        <h1 class="fd-modal__title">Modal Header</h1>
        <button (click)="onCloseModalClick()" class=" fd-button--secondary fd-modal__close"></button>
      </header>
      <div class="fd-modal__body">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
          aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
          Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
      </div>
      <footer class="fd-modal__footer">
        <div class="fd-modal__actions">
          <button (click)="onCloseModalClick()" class=" fd-button--secondary">Cancel</button>
          <button (click)="onCloseModalClick()" class=" fd-button--primary">Confirm</button>
        </div>
      </footer>
    </div>
  </div>
</div>
