// core/examples/luigi-example-svelte/src/routes/Home.svelte
<section class="fd-section">
  <div class="fd-section__header">
    <h1 class="fd-section__title">Home</h1>
  </div>
  <div class="fd-panel">
    { message }
  </div>
</section>
<script>
  import LuigiClient from '@kyma-project/luigi-client';
  import { onMount } from 'svelte';

  export let message;

  onMount(() => {
    LuigiClient.addInitListener(() => {
      message = 'Luigi Client initialized.'
    });
    LuigiClient.addContextUpdateListener(() => {
      message = 'Luigi Client updated.'
    });
  });
</script>

// core/examples/luigi-example-react/src/views/home.js
import React, { Component } from 'react';
import '../../node_modules/fiori-fundamentals/dist/fiori-fundamentals.css';
import LuigiClient from '@kyma-project/luigi-client';

export default class Home extends Component {
  constructor(props) {
    super(props);
    let luigiClient = LuigiClient;
    this.state = {
      message: ''
    };
    luigiClient.addInitListener(initialContext => {
      this.setState({
        message: 'Luigi Client initialized.'
      });
    });
    luigiClient.addContextUpdateListener(updatedContext => {
      this.setState({
        message: 'Luigi Client updated.'
      });
    });
  }
  render() {
    return (
      <div>
        <section className="fd-section">
          <div className="fd-section__header">
            <h1 className="fd-section__title">Home</h1>
          </div>
          <div className="fd-panel">{this.state.message}</div>
        </section>
      </div>
    );
  }
}
