// core/examples/luigi-example-angular/src/app/sample1/sample1.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-sample1',
  templateUrl: './sample1.component.html'
})
export class Sample1Component {
  constructor() {}
}

<div>
  <section class="fd-section">
    <div class="fd-section__header">
      <h1 class="fd-section__title">Sample 1</h1>
    </div>
    <div class="fd-panel">
      <div class="fd-panel__body">
        Luigi ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
        eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
        voluptua.
      </div>
    </div>
  </section>
</div>

// core/examples/luigi-example-react/src/views/sample1.js
import React, { Component } from 'react';

export default class Sample1 extends Component {
  render() {
    return (
      <div>
        <section className="fd-section">
          <div className="fd-section__header">
            <h1 className="fd-section__title">Sample 1</h1>
          </div>
          <div className="fd-panel">
            Luigi ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et
            dolore magna aliquyam erat, sed diam voluptua.
          </div>
        </section>
      </div>
    );
  }
}
