// core/examples/luigi-example-angular/src/app/sample2/sample2.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-sample2',
  templateUrl: './sample2.component.html'
})
export class Sample2Component {}

<div>
  <section class="fd-section">
    <div class="fd-section__header">
      <h1 class="fd-section__title">Sample 2</h1>
    </div>
    <div class="fd-panel">
      <div class="fd-panel__body">
        Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper
        suscipit lobortis nisl ut aliquip ex ea commodo consequat.
      </div>
    </div>
  </section>
</div>

<p>Sample2.html</p>
<!-- <button (click)="openModal()">Open modal</button> -->
<!-- <form action="sampleapp.html#/sample1">
  <button type="submit">Sample1</button>
</form> -->

<a routerLink="/sample1" routerLinkActive="active">Sample1</a>

// core/examples/luigi-example-react/src/views/sample2.js
import React, { Component } from 'react';

export default class Sample1 extends Component {
  render() {
    return (
      <div>
        <section className="fd-section">
          <div className="fd-section__header">
            <h1 className="fd-section__title">Sample 2</h1>
          </div>
          <div className="fd-panel">
            Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea
            commodo consequat.
          </div>
        </section>
      </div>
    );
  }
}
