// core/examples/luigi-example-vue/src/views/sample2.vue
<template>
  <div>
    <section class="fd-section">
      <div class="fd-section__header">
        <h1 class="fd-section__title">Sample 2</h1>
      </div>
      <div class="fd-panel">
        Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
      </div>
    </section>
  </div>
</template>

<script>
  export default {
    name: "sample2"
  }
</script>

<style scoped>
</style>

// core/examples/luigi-example-react/src/views/sample2.js
import React, { Component } from 'react';

export default class Sample1 extends Component {
  render() {
    return (
      <div>
        <section className="fd-section">
          <div className="fd-section__header">
            <h1 className="fd-section__title">Sample 2</h1>
          </div>
          <div className="fd-panel">
            Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea
            commodo consequat.
          </div>
        </section>
      </div>
    );
  }
}
