// core/examples/luigi-sample-angular/src/app/project/users/groups/customers/customers.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-customers',
  templateUrl: './customers.component.html',
  styleUrls: ['./customers.component.css']
})
export class CustomersComponent implements OnInit {
  constructor() {}

  ngOnInit() {}
}

<section class="fd-section">
  <div class="fd-section__header">
    <h1 class="fd-section__title">Customers</h1>
  </div>
  <div class="fd-panel">
    Customers content.
  </div>
</section>

// core/examples/luigi-sample-vue/src/views/projects/users/groups/customers.vue
<template>
  <div>
    <section class="fd-section">
      <div class="fd-section__header">
        <h1 class="fd-section__title">Customers</h1>
      </div>
      <div class="fd-panel">
        Customers content.
      </div>
    </section>
  </div>
</template>

<script>
  export default {
    name: "customers"
  }
</script>

<style scoped>

</style>
