// core/examples/luigi-sample-vue/src/views/projects/settings.vue
<template>
  <div>
    <section class="fd-section">
      <div class="fd-section__header">
        <h1 class="fd-section__title">Settings of {{ projectId }}</h1>
      </div>
      <div class="fd-panel">
        LuigiClient hasBack/GoBack:<br>
        {{luigiClient.linkManager().hasBack()}}
        {{hasBack}}
        <div v-if="hasBack">
          <p>
            <label>Modify goBackContext value, that you receive then via LuigiClient.addContextUpdateListener(): <br/>
              <input type="text" v-model="callbackValue"/>
            </label>
          </p>
          <p>
            <button class="fd-button" @click="goBack()">Click here</button> to go back to your preserved view.
          </p>
        </div>
        <div v-if="!hasBack">
          No go back state available, <a href="#" @click.prevent="luigiClient.linkManager().navigate('/projects/pr2')">Click
          here</a>
          to go to <i>project two</i>, where you can try out hasBack functionality
        </div>
      </div>
    </section>

    <section class="fd-section">
      <div class="fd-section__header">
        <h1 class="fd-section__title">Settings</h1>
      </div>
      <div class="fd-panel">
        Settings content.
      </div>
    </section>
  </div>
</template>

<script>
  export default {
    name: "settings",
    data: () => ({
      hasBack: false,
      callbackValue: 'default value'
    }),
    created () {
      this.luigiClient.addInitListener(() => {
        this.hasBack = this.luigiClient.linkManager().hasBack();
      });
    },
    methods: {
      goBack() {
        // going back with some sample callback context,
        // that will be handed over to previous view
        this.luigiClient.linkManager().goBack(this.callbackValue);
      }
    },
    props: {
      'projectId': {
        type: String,
        required: true,
        default: null
      }
    }
  }
</script>

<style scoped>

</style>

// core/examples/luigi-sample-angular/src/app/project/settings/settings.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { ActivatedRoute, Params } from '@angular/router';
import { LuigiClient } from '@kyma-project/luigi-client';

@Component({
  selector: 'app-settings',
  templateUrl: './settings.component.html',
  styleUrls: ['./settings.component.css']
})
export class SettingsComponent implements OnInit {
  luigiClient: LuigiClient;
  projectId: string;
  hasBack: boolean;
  callbackValue = 'default value';

  constructor(
    private activatedRoute: ActivatedRoute,
    private cdr: ChangeDetectorRef
  ) {}

  ngOnInit() {
    this.activatedRoute.params.subscribe((params: Params) => {
      this.projectId = params['projectId'];
    });
    this.luigiClient = LuigiClient;
    LuigiClient.addInitListener(() => {
      this.hasBack = LuigiClient.linkManager().hasBack();
      this.cdr.detectChanges();
    });
  }

  goBack() {
    // going back with some sample callback context,
    // that will be handed over to previous view
    this.luigiClient.linkManager().goBack(this.callbackValue);
  }
}

<section class="fd-section" *ngIf="nodeParams">
  <div class="fd-panel">
    <div class="fd-alert" role="alert">
      <span class="fd-status-label fd-status-label--available"></span> Called
      with params:<br />
      <pre data-testid="navigate_width_param">{{ nodeParams | json }}</pre>
    </div>
  </div>
  <div class="fd-panel" *ngIf="hasBack">
    Advanced: node Params and preserveView active. <br />
    <a
      href="javascript:void(0)"
      (click)="
        linkManager()
          .withParams({ foo: 'bar' })
          .navigate('/environments/env1', null, true)
      "
      >Go to /environments/env1 with preserveView</a
    >
    <br /><br />
    <a href="javascript:void(0)" (click)="linkManager().goBack()"
      >Go back: use default history method</a
    >
  </div>
</section>

<section class="fd-section" *ngIf="preservedViewCallbackContext">
  <div class="fd-panel">
    <div class="fd-alert" role="alert">
      <span class="fd-status-label fd-status-label--available"></span> Context
      received from linkManager().goBack():<br />
      <pre>{{ preservedViewCallbackContext | json }}</pre>
    </div>
  </div>
</section>

<section class="fd-section">
  <div class="fd-section__header">
    <h1 *ngIf="projectId" class="fd-section__title">
      Settings of {{ projectId }}
    </h1>
    <h1 *ngIf="!projectId" class="fd-section__title">Global Settings</h1>
  </div>

  <div class="fd-panel">
    LuigiClient hasBack/GoBack:<br />

    <div *ngIf="hasBack">
      <p>
        <label
          >Modify goBackContext value, that you receive then via
          LuigiClient.addContextUpdateListener(): <br />
          <input type="text" [(ngModel)]="callbackValue"
        /></label>
      </p>
      <p>
        <button class="fd-button" (click)="goBack()">Click here</button> to go
        back to your preserved view.
      </p>
    </div>
    <div *ngIf="!hasBack">
      No go back state available,
      <a
        href="javascript:void(0)"
        (click)="linkManager().navigate('/projects/pr2')"
        >Click here</a
      >
      to go to <i>project two</i>, where you can try out hasBack functionality
    </div>
  </div>
</section>
