// core/examples/luigi-example-react/src/App.js
import React from 'react';
import { Routes, Route } from 'react-router-dom';
import Home from './views/home.js';
import Sample1 from './views/sample1.js';
import Sample2 from './views/sample2.js';

const App = () => {
  return (
    <Routes>
      <Route path="/home" element={<Home />} />
      <Route path="/sample1" element={<Sample1 />} />
      <Route path="/sample2" element={<Sample2 />} />
    </Routes>
  )
}

export default App;

// core/examples/luigi-example-svelte/src/App.svelte
<div class="fd-page__content">
  <Router url="{url}">
    <Route path="" component="{Home}" />
    <Route path="/home/sample1" component="{Sample1}" />
    <Route path="/home/sample2" component="{Sample2}" />
  </Router>
</div>

<script>
  import { Router, Route } from "svelte-routing";
  import Home from "./routes/Home.svelte";
  import Sample1 from "./routes/Sample1.svelte";
  import Sample2 from "./routes/Sample2.svelte";
  export let url = "";
</script>
