// core/examples/luigi-example-angular/src/app/home/home.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import {
  addInitListener,
  addContextUpdateListener
} from '@kyma-project/luigi-client';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html'
})
export class HomeComponent implements OnInit {
  public message: string;

  constructor(private ref: ChangeDetectorRef) {}

  ngOnInit() {
    addInitListener(initialContext => {
      this.message = 'Luigi Client initialized.';
      if (!this.ref['destroyed']) {
        this.ref.detectChanges();
      }
    });
    addContextUpdateListener(updatedContext => {
      this.message = 'Luigi Client updated.';
      if (!this.ref['destroyed']) {
        this.ref.detectChanges();
      }
    });
  }
}

<div>
  <section class="fd-section">
    <div class="fd-section__header">
      <h1 class="fd-section__title">Home</h1>
    </div>
    <div class="fd-panel">
      {{ message }}
    </div>
  </section>
</div>

// core/examples/luigi-example-svelte/src/routes/Home.svelte
<section class="fd-section">
  <div class="fd-section__header">
    <h1 class="fd-section__title">Home</h1>
  </div>
  <div class="fd-panel">
    { message }
  </div>
</section>
<script>
  import LuigiClient from '@kyma-project/luigi-client';
  import { onMount } from 'svelte';

  export let message;

  onMount(() => {
    LuigiClient.addInitListener(() => {
      message = 'Luigi Client initialized.'
    });
    LuigiClient.addContextUpdateListener(() => {
      message = 'Luigi Client updated.'
    });
  });
</script>
