// core/examples/luigi-example-vue/src/views/home.vue
<template>
  <div>
    <section class="fd-section">
      <div class="fd-section__header">
        <h1 class="fd-section__title">Home</h1>
      </div>
      <div class="fd-panel">
        {{ message }}
      </div>
    </section>
  </div>
</template>

<script>
  export default {
    name: "home",
    data: () => ({
      message: ''
    }),
    components: {},
    methods: {},
    created () {
      this.luigiClient.addInitListener(initialContext => {
        this.message = 'Luigi Client initialized.'
      });
      this.luigiClient.addContextUpdateListener(updatedContext => {
        this.message = 'Luigi Client updated.'
      });
    }
  }
</script>

<style scoped lang="scss">
</style>

// core/examples/luigi-example-svelte/src/routes/Home.svelte
<section class="fd-section">
  <div class="fd-section__header">
    <h1 class="fd-section__title">Home</h1>
  </div>
  <div class="fd-panel">
    { message }
  </div>
</section>
<script>
  import LuigiClient from '@kyma-project/luigi-client';
  import { onMount } from 'svelte';

  export let message;

  onMount(() => {
    LuigiClient.addInitListener(() => {
      message = 'Luigi Client initialized.'
    });
    LuigiClient.addContextUpdateListener(() => {
      message = 'Luigi Client updated.'
    });
  });
</script>
